_name_or_path:
    value: ""
_wandb:
    value:
        cli_version: 0.18.5
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
        python_version: 3.9.20
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.9.20
            "5": 0.18.5
            "6": 4.26.0
            "8":
                - 5
            "12": 0.18.5
            "13": darwin-arm64
activation_function:
    value: gelu_new
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value: null
attn_pdrop:
    value: 0.1
auto_find_batch_size:
    value: false
bad_words_ids:
    value: null
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: 50256
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: None
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_pin_memory:
    value: true
ddp_bucket_cap_mb:
    value: None
ddp_find_unused_parameters:
    value: None
ddp_timeout:
    value: 1800
debug:
    value: '[]'
decoder_start_token_id:
    value: null
deepspeed:
    value: None
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
embd_pdrop:
    value: 0.1
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 50256
eval_accumulation_steps:
    value: None
eval_batch_size:
    value: 8
eval_delay:
    value: 0
eval_steps:
    value: None
evaluation_strategy:
    value: epoch
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: '[]'
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: None
full_determinism:
    value: false
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
greater_is_better:
    value: None
group_by_length:
    value: false
half_precision_backend:
    value: auto
hub_model_id:
    value: None
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
initializer_range:
    value: 0.02
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: None
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_norm_epsilon:
    value: 1e-05
learning_rate:
    value: 5e-05
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: false
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: passive
log_on_each_node:
    value: true
logging_dir:
    value: result/runs/Nov07_15-03-18_Franss-MacBook-Pro.local
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 500
logging_strategy:
    value: steps
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 20
max_steps:
    value: -1
metric_for_best_model:
    value: None
min_length:
    value: 0
model_type:
    value: gpt2
mp_parameters:
    value: ""
n_embd:
    value: 768
n_head:
    value: 12
n_inner:
    value: null
n_layer:
    value: 12
n_positions:
    value: 1024
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_return_sequences:
    value: 1
num_train_epochs:
    value: 3
optim:
    value: adamw_hf
optim_args:
    value: None
output_attentions:
    value: false
output_dir:
    value: result
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: null
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 4
per_gpu_eval_batch_size:
    value: None
per_gpu_train_batch_size:
    value: None
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: None
push_to_hub_organization:
    value: None
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
reorder_and_upcast_attn:
    value: false
repetition_penalty:
    value: 1
report_to:
    value: '[''tensorboard'', ''wandb'']'
resid_pdrop:
    value: 0.1
resume_from_checkpoint:
    value: None
return_dict:
    value: true
return_dict_in_generate:
    value: false
run_name:
    value: result
save_on_each_node:
    value: false
save_steps:
    value: 500
save_strategy:
    value: steps
save_total_limit:
    value: None
scale_attn_by_inverse_layer_idx:
    value: false
scale_attn_weights:
    value: true
seed:
    value: 42
sep_token_id:
    value: null
sharded_ddp:
    value: '[]'
skip_memory_metrics:
    value: true
summary_activation:
    value: null
summary_first_dropout:
    value: 0.1
summary_proj_to_labels:
    value: true
summary_type:
    value: cls_index
summary_use_proj:
    value: true
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: None
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: None
torch_compile_mode:
    value: None
torch_dtype:
    value: null
torchdynamo:
    value: None
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: None
train_batch_size:
    value: 4
transformers_version:
    value: 4.26.0
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_mps_device:
    value: false
vocab_size:
    value: 50257
warmup_ratio:
    value: 0
warmup_steps:
    value: 0
weight_decay:
    value: 0
xpu_backend:
    value: None
